apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "afterburner.fullname" . }}
  labels:
    {{- include "afterburner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "afterburner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "afterburner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "afterburner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: '{{ $value }}'
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.afterburner.deployment.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.afterburner.deployment.livenessProbe.httpGet.path }}
              port: {{ .Values.afterburner.deployment.livenessProbe.httpGet.port }}
              scheme: {{ .Values.afterburner.deployment.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.afterburner.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.afterburner.deployment.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.afterburner.deployment.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.afterburner.deployment.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.afterburner.deployment.readinessProbe.httpGet.path }}
              port: {{ .Values.afterburner.deployment.readinessProbe.httpGet.port }}
              scheme: {{ .Values.afterburner.deployment.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.afterburner.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.afterburner.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.afterburner.deployment.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
